from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QRadioButton


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(900, 500)
        MainWindow.setMinimumSize(QtCore.QSize(900, 500))
        MainWindow.setMaximumSize(QtCore.QSize(900, 500))
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 120, 611, 351))
        self.groupBox.setObjectName("groupBox")
        # Set the path of 3D reconstruction model
        self.textEdit_4 = QtWidgets.QTextEdit(self.groupBox)
        self.textEdit_4.hide()
        self.textEdit_4.setGeometry(QtCore.QRect(495, 208, 113, 51))
        self.textEdit_4.setObjectName("textEdit_4")

        self.log_2 = QtWidgets.QPlainTextEdit(self.groupBox)  # For set the backbone color is white
        self.log_2.setGeometry(QtCore.QRect(0, 15, 491, 335))
        self.log_2.setObjectName("log_2")

        self.groupBox.setStyleSheet("background-color: rgb(243, 243, 243);")

        # 创建一个新的 QWidget 作为 QOpenGLWidget 的父部件
        self.widget = QtWidgets.QWidget(self.groupBox)
        self.widget.setGeometry(QtCore.QRect(0, 15, 491, 335))
        self.widget.setStyleSheet("background-color: white;")  # 设置 QWidget 的背景色为白

        self.dense_9 = QtWidgets.QPushButton(self.groupBox)
        self.dense_9.setGeometry(QtCore.QRect(495, 15, 113, 31))
        self.dense_9.setObjectName("dense_9")
        self.checkBox = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox.setGeometry(QtCore.QRect(495, 55, 101, 16))
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_2.setGeometry(QtCore.QRect(495, 90, 101, 16))
        self.checkBox_2.setObjectName("checkBox_2")
        self.dense_4 = QtWidgets.QPushButton(self.groupBox)
        self.dense_4.setGeometry(QtCore.QRect(495, 120, 113, 31))
        self.dense_4.setObjectName("dense_4")
        self.dense_7 = QtWidgets.QPushButton(self.groupBox)
        self.dense_7.setGeometry(QtCore.QRect(495, 170, 113, 31))
        self.dense_7.setObjectName("dense_7")
        self.checkBox_3 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_3.setGeometry(QtCore.QRect(495, 210, 101, 16))
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_4 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_4.setGeometry(QtCore.QRect(495, 240, 101, 16))
        self.checkBox_4.setObjectName("checkBox_4")
        self.dense_5 = QtWidgets.QPushButton(self.groupBox)
        self.dense_5.setGeometry(QtCore.QRect(495, 270, 113, 31))
        self.dense_5.setObjectName("dense_5")
        self.dense_6 = QtWidgets.QPushButton(self.groupBox)
        self.dense_6.setGeometry(QtCore.QRect(495, 320, 113, 31))
        self.dense_6.setObjectName("dense_6")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(330, 20, 291, 91))
        self.groupBox_2.setObjectName("groupBox_2")

        self.locateImg = QtWidgets.QPushButton(self.groupBox_2)
        self.locateImg.setGeometry(QtCore.QRect(180, 20, 112, 31))
        self.locateImg.setObjectName("locateImg")
        self.dense_8 = QtWidgets.QPushButton(self.groupBox_2)
        self.dense_8.setGeometry(QtCore.QRect(180, 60, 112, 31))
        self.dense_8.setObjectName("dense_8")
        self.locateSparse_2 = QtWidgets.QPushButton(self.groupBox_2)
        self.locateSparse_2.setGeometry(QtCore.QRect(0, 20, 81, 31))
        self.locateSparse_2.setObjectName("locateSparse_2")
        self.locateSparse = QtWidgets.QPushButton(self.groupBox_2)
        self.locateSparse.setGeometry(QtCore.QRect(90, 20, 81, 31))
        self.locateSparse.setObjectName("locateSparse")
        self.dense = QtWidgets.QPushButton(self.groupBox_2)
        self.dense.setGeometry(QtCore.QRect(90, 60, 81, 31))
        self.dense.setObjectName("dense")
        self.locateSparse_3 = QtWidgets.QPushButton(self.groupBox_2)
        self.locateSparse_3.setGeometry(QtCore.QRect(0, 60, 81, 31))
        self.locateSparse_3.setObjectName("locateSparse_3")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(630, 20, 261, 451))
        self.groupBox_3.setObjectName("groupBox_3")
        self.log = QtWidgets.QPlainTextEdit(self.groupBox_3)
        self.log.setGeometry(QtCore.QRect(0, 60, 261, 401))
        self.log.setObjectName("log")
        self.dense_2 = QtWidgets.QPushButton(self.groupBox_3)
        self.dense_2.setGeometry(QtCore.QRect(10, 20, 101, 31))
        self.dense_2.setObjectName("dense_2")
        self.dense_3 = QtWidgets.QPushButton(self.groupBox_3)
        self.dense_3.setGeometry(QtCore.QRect(140, 20, 101, 31))
        self.dense_3.setObjectName("dense_3")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 20, 311, 91))
        self.groupBox_4.setObjectName("groupBox_4")

        self.textEdit_3 = QtWidgets.QTextEdit(self.groupBox_4)  # Show the path of dataset
        self.textEdit_3.setGeometry(QtCore.QRect(84, 58, 220, 27))
        self.textEdit_3.setObjectName("textEdit_3")
        self.logText = QtWidgets.QLabel(self.groupBox_4)
        self.logText.setGeometry(QtCore.QRect(10, 20, 140, 21))
        self.logText.setObjectName("logText")
        self.locateSparse_4 = QtWidgets.QRadioButton(self.groupBox_4)
        self.locateSparse_4.setGeometry(QtCore.QRect(160, 17, 71, 26))
        self.locateSparse_4.setObjectName("locateSparse_4")
        self.locateSparse_6 = QtWidgets.QRadioButton(self.groupBox_4)
        self.locateSparse_6.setGeometry(QtCore.QRect(250, 17, 71, 26))
        self.locateSparse_6.setObjectName("locateSparse_6")
        self.locateSparse_5 = QtWidgets.QPushButton(self.groupBox_4)
        self.locatecSparse_5.setGeometry(QtCore.QRect(10, 58, 71, 26))
        self.locateSparse_5.setObjectName("locateSparse_5")

        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Point-Line Localization and 3D Reconstruction System"))
        self.groupBox.setTitle(_translate("MainWindow", "可视化"))
        self.checkBox_4.setText(_translate("MainWindow", "导入线模型"))
        self.checkBox_3.setText(_translate("MainWindow", "导入点模型"))
        self.dense_5.setText(_translate("MainWindow", "显示模型参数"))
        self.dense_7.setText(_translate("MainWindow", "导入模型"))
        self.dense_4.setText(_translate("MainWindow", "导出模型"))
        self.dense_6.setText(_translate("MainWindow", "保存重建"))
        self.checkBox.setText(_translate("MainWindow", "显示点重建"))
        self.checkBox_2.setText(_translate("MainWindow", "显示线重建"))
        self.dense_9.setText(_translate("MainWindow", "快速三维重建"))
        self.groupBox_2.setTitle(_translate("MainWindow", "定位与三维重建"))
        self.locateImg.setText(_translate("MainWindow", "定位及稀疏重建"))
        self.dense_8.setText(_translate("MainWindow", "稠密三维重建"))
        self.locateSparse_2.setText(_translate("MainWindow", "参数设置"))
        self.locateSparse.setText(_translate("MainWindow", "特征描述"))
        self.dense.setText(_translate("MainWindow", "特征匹配"))
        self.locateSparse_3.setText(_translate("MainWindow", "视频预处理"))
        self.groupBox_3.setTitle(_translate("MainWindow", "日志输出"))
        self.dense_2.setText(_translate("MainWindow", "保存日志"))
        self.dense_3.setText(_translate("MainWindow", "清空日志"))
        self.groupBox_4.setTitle(_translate("MainWindow", "输入数据"))
        # self.locateSparse_4.setText(_translate("MainWindow", "数据路径"))
        self.logText.setText(_translate("MainWindow", "请选择输入数据类型："))
        self.locateSparse_6.setText(_translate("MainWindow", "图片"))
        self.locateSparse_4.setText(_translate("MainWindow", "视频"))
        self.locateSparse_5.setText(_translate("MainWindow", "数据路径"))
