from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(790, 442)
        MainWindow.setMinimumSize(QtCore.QSize(120, 0))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget.setObjectName("centralwidget")
        self.cameramodel = QtWidgets.QLabel(self.centralwidget)
        self.cameramodel.setGeometry(QtCore.QRect(160, 370, 131, 41))
        self.cameramodel.setAlignment(QtCore.Qt.AlignCenter)
        self.cameramodel.setObjectName("cameramodel")
        self.para = QtWidgets.QLabel(self.centralwidget)
        self.para.setGeometry(QtCore.QRect(80, 170, 70, 20))
        self.para.setObjectName("para")
        self.cameraPara = QtWidgets.QLabel(self.centralwidget)
        self.cameraPara.setGeometry(QtCore.QRect(80, 380, 70, 20))
        self.cameraPara.setObjectName("cameraPara")
        self.comboBoxCamera = QtWidgets.QComboBox(self.centralwidget)
        self.comboBoxCamera.setGeometry(QtCore.QRect(300, 380, 341, 20))
        self.comboBoxCamera.setObjectName("comboBoxCamera")
        self.paraSave = QtWidgets.QPushButton(self.centralwidget)
        self.paraSave.setGeometry(QtCore.QRect(650, 320, 41, 31))
        # self.paraSave.setMaximumSize(QtCore.QSize(120, 16777215))
        # self.paraSave.setAlignment(QtCore.Qt.AlignCenter)
        self.paraSave.setObjectName("paraSave")
        self.paraReturn = QtWidgets.QPushButton(self.centralwidget)
        self.paraReturn.setGeometry(QtCore.QRect(700, 320, 41, 31))
        # self.paraReturn.setMaximumSize(QtCore.QSize(100, 16777215))
        # self.paraReturn.setAlignment(QtCore.Qt.AlignCenter)
        self.paraReturn.setObjectName("paraReturn")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(160, 20, 481, 331))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.nnValue = QtWidgets.QDoubleSpinBox(self.widget)
        self.nnValue.setMaximumSize(QtCore.QSize(70, 16777215))
        self.nnValue.setObjectName("nnValue")
        self.gridLayout.addWidget(self.nnValue, 3, 2, 1, 1)

        self.LabelDetector = QtWidgets.QLabel(self.widget)
        self.LabelDetector.setObjectName("LabelDetector")
        self.gridLayout.addWidget(self.LabelDetector, 0, 1, 1, 2)

        self.comboBoxDetector = QtWidgets.QComboBox(self.widget)
        self.comboBoxDetector.setObjectName("comboBoxDetector")
        self.gridLayout.addWidget(self.comboBoxDetector, 0, 1, 1, 2)

        self.checkBoxGpu = QtWidgets.QCheckBox(self.widget)
        self.checkBoxGpu.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBoxGpu.setObjectName("checkBoxGpu")
        self.gridLayout.addWidget(self.checkBoxGpu, 5, 1, 1, 2)
        self.detector = QtWidgets.QLabel(self.widget)
        self.detector.setMinimumSize(QtCore.QSize(0, 20))
        self.detector.setMaximumSize(QtCore.QSize(120, 16777215))
        self.detector.setAlignment(QtCore.Qt.AlignCenter)
        self.detector.setObjectName("detector")
        self.gridLayout.addWidget(self.detector, 0, 0, 1, 1)
        self.sample = QtWidgets.QLabel(self.widget)
        self.sample.setMaximumSize(QtCore.QSize(120, 16777215))
        self.sample.setAlignment(QtCore.Qt.AlignCenter)
        # self.sample.displayText()
        self.sample.setObjectName("sample")
        self.gridLayout.addWidget(self.sample, 4, 0, 1, 1)
        self.nn = QtWidgets.QLabel(self.widget)
        self.nn.setMaximumSize(QtCore.QSize(120, 16777215))
        self.nn.setAlignment(QtCore.Qt.AlignCenter)
        self.nn.setObjectName("nn")
        self.gridLayout.addWidget(self.nn, 3, 0, 1, 1)
        self.horizontalSliderSample = QtWidgets.QSlider(self.widget)
        self.horizontalSliderSample.setMinimumSize(QtCore.QSize(100, 10))
        self.horizontalSliderSample.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderSample.setObjectName("horizontalSliderSample")
        self.gridLayout.addWidget(self.horizontalSliderSample, 4, 1, 1, 1)

        # self.sampleValue = QtWidgets.QLineEdit(self.widget)
        self.sampleValue = QtWidgets.QSpinBox(self.widget)
        self.sampleValue.setMinimumSize(QtCore.QSize(0, 20))
        self.sampleValue.setMaximumSize(QtCore.QSize(70, 16777215))
        # self.sampleValue.setValue(slSample)  # 设置显示内容
        self.sampleValue.setObjectName("sampleValue")
        self.gridLayout.addWidget(self.sampleValue, 4, 2, 1, 1)

        self.nms = QtWidgets.QLabel(self.widget)
        self.nms.setMaximumSize(QtCore.QSize(120, 16777215))
        self.nms.setAlignment(QtCore.Qt.AlignCenter)
        self.nms.setObjectName("nms")
        self.gridLayout.addWidget(self.nms, 2, 0, 1, 1)
        self.gpu = QtWidgets.QLabel(self.widget)
        self.gpu.setMaximumSize(QtCore.QSize(100, 16777215))
        self.gpu.setAlignment(QtCore.Qt.AlignCenter)
        self.gpu.setObjectName("gpu")
        self.gridLayout.addWidget(self.gpu, 5, 0, 1, 1)

        self.config = QtWidgets.QLabel(self.widget)
        self.config.setMaximumSize(QtCore.QSize(120, 16777215))
        self.config.setAlignment(QtCore.Qt.AlignCenter)
        self.config.setObjectName("config")
        self.gridLayout.addWidget(self.config, 1, 0, 1, 1)

        self.horizontalSliderNMS = QtWidgets.QSlider(self.widget)
        self.horizontalSliderNMS.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderNMS.setObjectName("horizontalSliderNMS")
        self.gridLayout.addWidget(self.horizontalSliderNMS, 2, 1, 1, 1)

        self.horizontalSliderConf = QtWidgets.QSlider(self.widget)
        self.horizontalSliderConf.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderConf.setObjectName("horizontalSliderConf")
        self.gridLayout.addWidget(self.horizontalSliderConf, 1, 1, 1, 1)

        self.confValue = QtWidgets.QDoubleSpinBox(self.widget)
        self.confValue.setMaximumSize(QtCore.QSize(70, 16777215))
        self.confValue.setObjectName("confValue")
        self.gridLayout.addWidget(self.confValue, 1, 2, 1, 1)

        self.nmsValue = QtWidgets.QSpinBox(self.widget)
        self.nmsValue.setMaximumSize(QtCore.QSize(70, 16777215))
        self.nmsValue.setObjectName("nmsValue")
        self.gridLayout.addWidget(self.nmsValue, 2, 2, 1, 1)
        self.horizontalSliderNN = QtWidgets.QSlider(self.widget)
        self.horizontalSliderNN.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderNN.setObjectName("horizontalSliderNN")
        self.gridLayout.addWidget(self.horizontalSliderNN, 3, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Paremeter Set"))
        self.cameramodel.setText(_translate("MainWindow", "相机模型"))
        self.para.setText(_translate("MainWindow", "检测参数"))
        self.cameraPara.setText(_translate("MainWindow", "相机参数"))
        self.paraSave.setText(_translate("MainWindow", "保存"))
        self.paraReturn.setText(_translate("MainWindow", "返回"))
        self.checkBoxGpu.setText(_translate("MainWindow", "yes"))
        self.detector.setText(_translate("MainWindow", "检测器"))
        self.sample.setText(_translate("MainWindow", "采样点数量"))
        self.nn.setText(_translate("MainWindow", "nn_threshold"))
        self.nms.setText(_translate("MainWindow", "nms_threshold"))
        self.gpu.setText(_translate("MainWindow", "use_gpu"))
        self.config.setText(_translate("MainWindow", "conf_threshold"))
